name: Curiously Defunct
favicon: null
layout_spectrum: 0.28415
typography_spectrum: 0.46339
title: 'Curiously Defunct | Functional Dysphoria'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77405836-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c8c7c2'
    - '#47443f'
    - '#817c78'
    - '#0b0f12'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.2484256539028138
  rhythmicContrast: 0.5
purpose: []
